import Foundation
import SiltCore

/// What Silt knows about a file or folder, from its name and surroundings:
/// a short tag for the tree, and a fuller explanation for the inspector.
struct Guidance: Equatable {
    enum Safety: Equatable {
        case safe     // rebuilt or re-downloaded on demand
        case review   // probably unneeded, but only you can say
        case keep     // leave it alone
    }

    let tag: String
    let title: String
    let detail: String
    let safety: Safety
}

enum Guide {
    /// Lock held. `name` is the entry's name; `path` is built only when a
    /// rule needs it.
    static func classify(tree: Tree, entry i: UInt32, name: String, path: () -> String) -> Guidance? {
        let e = tree.entry(i)
        if e.isDir {
            return folder(tree: tree, entry: e, name: name, path: path)
        }
        return file(name: name)
    }

    private static func has(_ tree: Tree, dir: UInt32, child: String) -> Bool {
        let d = tree.dir(dir)
        let want = Array(child.utf8)
        for k in d.first..<(d.first + d.count) {
            let c = tree.entry(k)
            if c.isRemoved || Int(c.name_len) != want.count { continue }
            if want.withUnsafeBufferPointer({ memcmp(silt_name_ptr(tree.raw, c.name), $0.baseAddress!, want.count) }) == 0 {
                return true
            }
        }
        return false
    }

    /// The install command the project's lockfile implies.
    private static func installCommand(_ tree: Tree, _ e: silt_entry) -> String {
        if sibling(tree, of: e, "pnpm-lock.yaml") { return "pnpm install" }
        if sibling(tree, of: e, "yarn.lock") { return "yarn install" }
        if sibling(tree, of: e, "bun.lockb") || sibling(tree, of: e, "bun.lock") { return "bun install" }
        return "npm install"
    }

    /// " The project last changed 3 months ago." — ignoring the build folder
    /// itself, so it says how dormant the project is.
    private static func projectNote(_ tree: Tree, _ e: silt_entry) -> String {
        guard e.parent != NONE else { return "" }
        let p = tree.dir(e.parent)
        var newest: UInt32 = 0
        for k in p.first..<(p.first + p.count) {
            let c = tree.entry(k)
            if c.isRemoved || (c.isDir && c.aux == e.aux) { continue }
            newest = max(newest, c.isDir ? tree.dir(c.aux).newest : c.aux)
        }
        guard newest > 0 else { return "" }
        let age = Date().timeIntervalSince1970 - TimeInterval(newest)
        if age > 90 * 86400 { return " The project hasn’t changed in \(Fmt.age(newest).replacingOccurrences(of: " ago", with: "")), so you may not need these soon." }
        return " The project last changed \(Fmt.age(newest))."
    }

    private static func sibling(_ tree: Tree, of e: silt_entry, _ name: String) -> Bool {
        e.parent != NONE && has(tree, dir: e.parent, child: name)
    }

    private static func folder(tree: Tree, entry e: silt_entry, name: String, path: () -> String) -> Guidance? {
        switch name {
        case "node_modules":
            return sibling(tree, of: e, "package.json")
                ? Guidance(tag: "Dependencies", title: "JavaScript dependencies",
                           detail: "Installed packages for the project next to it. `\(installCommand(tree, e))` puts them back."
                               + projectNote(tree, e),
                           safety: .safe)
                : Guidance(tag: "Orphaned", title: "Orphaned dependencies",
                           detail: "There's no package.json beside it, so no project will reinstall these.",
                           safety: .safe)
        case "DerivedData":
            return Guidance(tag: "Build output", title: "Xcode build output",
                            detail: "Intermediate build products. Xcode recreates them on the next build.", safety: .safe)
        case ".build":
            if sibling(tree, of: e, "Package.swift") {
                return Guidance(tag: "Build output", title: "SwiftPM build output",
                                detail: "Rebuilt by `swift build`.", safety: .safe)
            }
        case "Pods":
            if sibling(tree, of: e, "Podfile") {
                return Guidance(tag: "Dependencies", title: "CocoaPods", detail: "Reinstalled by `pod install`.", safety: .safe)
            }
        case ".next", ".nuxt", ".turbo", ".parcel-cache", ".svelte-kit", ".angular", "__pycache__", ".pytest_cache",
             ".mypy_cache", ".ruff_cache", ".gradle":
            return Guidance(tag: "Cache", title: "Build cache",
                            detail: "Generated by your tools and recreated the next time they run.", safety: .safe)
        case ".venv", "venv":
            if has(tree, dir: e.aux, child: "pyvenv.cfg") {
                return Guidance(tag: "Environment", title: "Python virtual environment",
                                detail: "Recreate it from your requirements or lockfile.", safety: .review)
            }
        case ".git":
            return Guidance(tag: "History", title: "Git repository data",
                            detail: "Every commit and branch of this project. Deleting it erases the history; `git gc` can shrink it instead.",
                            safety: .keep)
        case "Caches":
            return Guidance(tag: "Cache", title: "App caches",
                            detail: "Apps rebuild these as needed. Quit large apps before clearing them.", safety: .safe)
        case ".Trash", ".Trashes":
            return Guidance(tag: "Trash", title: "Trash",
                            detail: "Already deleted, but still using space until the Trash is emptied.", safety: .safe)
        case "Downloads":
            return Guidance(tag: "", title: "Downloads",
                            detail: "Everything you've downloaded. Installers and archives here are usually safe to thin out.",
                            safety: .review)
        case "iOS DeviceSupport", "watchOS DeviceSupport", "tvOS DeviceSupport", "visionOS DeviceSupport":
            return Guidance(tag: "Cache", title: "Device support files",
                            detail: "Debug symbols Xcode copies from devices. Re-copied the next time you connect one.",
                            safety: .safe)
        case "Archives" where path().hasSuffix("Developer/Xcode/Archives"):
            return Guidance(tag: "", title: "Xcode archives",
                            detail: "Past app builds. Keep any you might need for crash symbolication.", safety: .review)
        default:
            break
        }
        // Cargo target folders, wherever they live.
        if has(tree, dir: e.aux, child: ".rustc_info.json") {
            return Guidance(tag: "Build output", title: "Rust build output",
                            detail: "A cargo target folder. The next `cargo build` recreates it, though a full rebuild can take a while."
                                + (sibling(tree, of: e, "Cargo.toml") ? projectNote(tree, e) : ""),
                            safety: .safe)
        }
        let ext = (name as NSString).pathExtension.lowercased()
        if ext == "app" {
            return Guidance(tag: "", title: "Application",
                            detail: "Moving an app to the Trash uninstalls it. Its settings and caches in ~/Library may stay behind.",
                            safety: .review)
        }
        if ext == "xcarchive" {
            return Guidance(tag: "", title: "Xcode archive", detail: "A past app build.", safety: .review)
        }
        return nil
    }

    private static func file(name: String) -> Guidance? {
        let ext = (name as NSString).pathExtension.lowercased()
        switch ext {
        case "dmg", "pkg", "mpkg", "iso", "xip":
            return Guidance(tag: "Installer", title: "Installer",
                            detail: "Once the software is installed, the installer is rarely needed again.", safety: .review)
        case "ipsw":
            return Guidance(tag: "Firmware", title: "iPhone or iPad firmware",
                            detail: "Finder downloads it again when a device needs it.", safety: .safe)
        case "gguf", "safetensors", "ckpt", "pth", "onnx":
            return Guidance(tag: "Model", title: "Model weights",
                            detail: "A local AI model. Delete it if you no longer run it; you can download it again.",
                            safety: .review)
        case "crash", "ips", "hprof", "core":
            return Guidance(tag: "Diagnostic", title: "Crash or memory dump",
                            detail: "Diagnostic output. Rarely needed after the problem is solved.", safety: .safe)
        default:
            return nil
        }
    }
}
